[ISSUE #143] add integration test for restlight
esastack/esa-restlight pull request #148
Opened 2022-04-22 09:12 UTC by brotherlu-xcq

### Describe what this PR does / why we need it
add integration test for restlight.

### Does this pull request fix one issue?

### Describe how you did it

Fixes #143 

### Describe how to verify it
check and run the workflow

### Special notes for reviews
no

2022-04-24 02:28 UTC, alalag1 commented
LGTM

2022-04-25 03:15 UTC, LCDZhao-Z commented on restlight-integration-test/springmvc-test/src/main/java/io/esastack/restlight/integration/cases/controller/FailFastController.java
> +public class FailFastController implements RestlightBizExecutorAware {
Is it necessary to implement RestlightBizExecutorAware？

2022-04-25 03:20 UTC, alalag1 requested changes

2022-04-25 03:20 UTC, alalag1 commented on restlight-integration-test/springmvc-test/src/main/java/io/esastack/restlight/integration/cases/controller/ExceptionController.java
> + * @author chenglu
do not import your name plz

2022-04-25 03:20 UTC, alalag1 commented on restlight-integration-test/springmvc-test/src/main/java/io/esastack/restlight/integration/cases/controller/ExceptionController.java
> + * @author chenglu
same with other classes. check plz

2022-04-25 03:21 UTC, LCDZhao-Z commented on restlight-integration-test/springmvc-test/src/main/java/io/esastack/restlight/integration/cases/controller/FilterController.java
> +        return UserData.Builder.aRestResult()
Does aRestResult() have any special meaning? Logically, it is not necessary to call this method to build UserData.

2022-04-25 03:28 UTC, LCDZhao-Z commented on restlight-integration-test/springmvc-test/src/main/java/io/esastack/restlight/integration/cases/inteceptor/AttributeInterceptor.java
> +public class AttributeInterceptor implements InternalInterceptor {
Is it necessary to set a separate package for AttributeInterceptor  when the package is not set independently for filters and some paramResolvers?

2022-04-25 03:30 UTC, LCDZhao-Z commented on restlight-integration-test/springmvc-test/src/main/java/io/esastack/restlight/integration/cases/resolver/GlobalExceptionResolver.java
> +public class GlobalExceptionResolver implements ExceptionResolver<IllegalArgumentException> {
Is it necessary to set a separate package for GlobalExceptionResolver  when the package is not set independently for filters and some paramResolvers?

2022-04-25 03:31 UTC, LCDZhao-Z commented on restlight-integration-test/springmvc-test/src/main/java/io/esastack/restlight/integration/cases/resolver/CustomExceptionHandler.java
> +public class CustomExceptionHandler {
How does it work?

2022-04-25 03:54 UTC, LCDZhao-Z commented on restlight-integration-test/springmvc-test/src/main/java/io/esastack/restlight/integration/cases/config/SerializeConfig.java
> +        return new JacksonHttpBodySerializer() {
Is it needed to inject JacksonHttpBodySerializer when it had been loaded by spi automatically in Deployments.loadDefaultSerializersIfNecessary() ?

2022-04-25 07:08 UTC, merged