convert empty string to empty collection or array
esastack/esa-restlight pull request #54
Opened 2021-05-11 12:45 UTC by Mkabaka

2021-05-12 03:21 UTC, alalag1 requested changes
Make ConverterUtils provide a converter with explicit rules
- convert `null` to `null`
- convert `empty string` type by type()
  - throw an exception if the target type is a primitive type
  - convert to empty `Collection` or `Array`

> plz do not change the impoprts with '*'

2021-05-14 03:00 UTC, alalag1 requested changes

2021-05-14 03:23 UTC, Mkabaka commented on restlight-jaxrs-provider/src/main/java/esa/restlight/jaxrs/util/JaxrsMappingUtils.java
> +    }
done!

2021-05-14 03:25 UTC, Mkabaka commented on restlight-core/src/main/java/esa/restlight/core/resolver/arg/AbstractNameAndValueArgumentResolver.java
> +        } else if (Optional.class.isAssignableFrom(param.type())) {
done!

2021-05-14 03:26 UTC, Mkabaka commented on restlight-core/src/main/java/esa/restlight/core/resolver/arg/AbstractNameAndValueArgumentResolver.java
>          }
done~

2021-05-14 03:36 UTC, Mkabaka commented on restlight-core/src/main/java/esa/restlight/core/resolver/arg/AbstractRequestBodyArgumentResolver.java
> +                        .toString(StandardCharsets.UTF_8));
We'll resolve it in https://github.com/esastack/esa-restlight/issues/31

2021-05-14 03:50 UTC, Mkabaka commented on restlight-common/src/main/java/esa/restlight/core/util/ConverterUtils.java
> +                ? null : BigDecimal.valueOf(Double.parseDouble(v)));
done!

2021-05-14 06:09 UTC, Mkabaka commented on restlight-core/src/main/java/esa/restlight/core/resolver/arg/AbstractNameAndValueArgumentResolver.java
> +        boolean hasDefaultValue = false;
done!

2021-05-14 06:09 UTC, Mkabaka commented on restlight-common/src/main/java/esa/restlight/core/util/ConverterUtils.java
> +
done!

2021-05-14 06:19 UTC, Mkabaka commented on restlight-core/src/main/java/esa/restlight/core/resolver/arg/NameAndValue.java
>      }
This constructor should be retained.

2021-05-14 06:44 UTC, alalag1 approved these changes

2021-05-14 06:44 UTC, alalag1 commented on restlight-common/src/main/java/esa/restlight/core/util/ConverterUtils.java
> +        STRING_CONVERTER_MAP.put(char.class, v -> v == null ? null : v.length() >= 1 ? v.charAt(0) : v);
`v.length() > 0`

2021-05-14 06:52 UTC, Mkabaka commented on restlight-common/src/main/java/esa/restlight/core/util/ConverterUtils.java
> +        STRING_CONVERTER_MAP.put(char.class, v -> v == null ? null : v.length() >= 1 ? v.charAt(0) : v);
done!

2021-05-14 06:55 UTC, merged