[imp]replace the constant JDK_DEFAULT_REJECT_HANDLER init static code
esastack/esa-restlight pull request #73
Opened 2021-07-06 09:19 UTC by fkinjava

[imp]replace the constant JDK_DEFAULT_REJECT_HANDLER init static code in BaseDeployments

2021-07-06 10:17 UTC, fkinjava commented
[imp]replace the constant JDK_DEFAULT_REJECT_HANDLER init static code in BaseDeployments

2021-07-07 11:16 UTC, alalag1 requested changes

2021-07-07 11:16 UTC, alalag1 commented on restlight-server/src/main/java/esa/restlight/server/BaseDeployments.java
> +            LoggerUtils.logger().error("Could not find the field named defaultHandler in ThreadPoolExecutor, JDK_DEFAULT_REJECT_HANDLER will be set to ThreadPoolExecutor$AbortPolicy.class", e);
What about printing the log by debug-level and fallbacking to `ThreadPoolExecutor.getRejectedExecutionHandler().getClass()` if failed to retrieve `JDK_DEFAULT_REJECT_HANDLER` by reflection

2021-07-07 11:19 UTC, alalag1 commented
@fkinjava there are checkstyle errors, take a look plz

2021-07-08 01:42 UTC, alalag1 commented
@fkinjava thx a lot

2021-07-08 01:42 UTC, merged